In [1]:
import numpy as np

In [2]:
#Vector
y = np.array([1,2,3])
x = np.array([4,5,6])

In [3]:
y + x

array([5, 7, 9])

In [4]:
y - x

array([-3, -3, -3])

In [5]:
# dot product
np.dot(y,x)

32

In [6]:
#hadamard product
y * x

array([ 4, 10, 18])

In [7]:
#Matrix
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3]])


In [8]:
a.shape

(2, 3)

In [9]:
b.shape

(1, 3)

In [10]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [11]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [12]:
#hadamard product
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [13]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
a.shape

(2, 3)